name = "NapkinLean"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["NapkinLean"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
relaxedAutoImplicit = false
maxSynthPendingDepth = 3
warn.sorry = false

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.29.0"

[[require]]
name = "verso"
git = "https://github.com/leanprover/verso"
rev = "7ae82ac"

[[lean_lib]]
name = "NapkinLean"
