import Mathlib.RingTheory.Ideal.Quotient.Basic
import Mathlib.RingTheory.Ideal.Span
import Mathlib.RingTheory.PrincipalIdealDomain
import Mathlib.Tactic

/-! # Chapter 4: Rings and ideals

This file formalizes Chapter 4 of Evan Chen's
*An Infinitely Large Napkin*, covering rings, fields,
ring homomorphisms, ideals, and quotient rings.

## References
* [Evan Chen, *An Infinitely Large Napkin*](https://venhance.github.io/napkin/Napkin.pdf), Chapter 4
-/

/-! ## Section 4.3: Definition and examples of rings

Napkin Definition 4.3.1: A **ring** (R, +, ×) is a set R equipped
with addition (forming an abelian group) and multiplication (associative with
identity), satisfying the distributive laws.

In Mathlib, `Ring R` extends `Semiring R` and `AddCommGroup R`.
-/
section RingDefinition

#check (Ring : Type _ → Type _)
#check (CommRing : Type _ → Type _)

end RingDefinition

/-! ### Examples of rings (Napkin Example 4.3.2) -/
section RingExamples

-- The integers
example : CommRing ℤ := inferInstance

-- ℤ/nℤ
example (n : ℕ) : CommRing (ZMod n) := inferInstance

-- Polynomials over a ring
noncomputable example (R : Type*) [CommRing R] : CommRing (Polynomial R) := inferInstance

-- Matrices
example (n : ℕ) (R : Type*) [CommRing R] [DecidableEq (Fin n)] :
    Ring (Matrix (Fin n) (Fin n) R) := inferInstance

end RingExamples

/-! ## Section 4.4: Fields

Napkin Definition 4.4.1: A **field** is a commutative ring in which
every nonzero element has a multiplicative inverse.

In Mathlib, `Field K` extends `CommRing K` and `DivisionRing K`.
-/
section Fields

#check (Field : Type _ → Type _)

-- Examples
example : Field ℚ := inferInstance
noncomputable example : Field ℝ := inferInstance
noncomputable example : Field ℂ := inferInstance
example (p : ℕ) [Fact (Nat.Prime p)] : Field (ZMod p) := inferInstance

end Fields

/-! ## Section 4.5: Ring homomorphisms

Napkin Definition 4.5.1: A **ring homomorphism** φ : R →+* S is a
map satisfying φ(a + b) = φ(a) + φ(b), φ(a * b) = φ(a) * φ(b),
and φ(1) = 1.

In Mathlib, this is `RingHom` (notation: `R →+* S`).
-/
section RingHomomorphisms

variable {R S : Type*} [Ring R] [Ring S]

#check @RingHom

-- A ring homomorphism preserves the key operations
recall RingHom.map_add {α : Type*} {β : Type*}
    [NonAssocSemiring α] [NonAssocSemiring β] (f : α →+* β) (a b : α) :
    f (a + b) = f a + f b
recall RingHom.map_mul {α : Type*} {β : Type*}
    [NonAssocSemiring α] [NonAssocSemiring β] (f : α →+* β) (a b : α) :
    f (a * b) = f a * f b
recall RingHom.map_one {α : Type*} {β : Type*}
    [NonAssocSemiring α] [NonAssocSemiring β] (f : α →+* β) : f 1 = 1
recall RingHom.map_zero {α : Type*} {β : Type*}
    [NonAssocSemiring α] [NonAssocSemiring β] (f : α →+* β) : f 0 = 0

end RingHomomorphisms

/-! ## Section 4.6: Ideals

Napkin Definition 4.6.1: An **ideal** I of a ring R is a nonempty
subset closed under addition and closed under multiplication by any
element of R (i.e. I is a submodule of R over itself).

In Mathlib, `Ideal R` is defined as `Submodule R R`.
-/
section Ideals

variable {R : Type*} [CommRing R]

-- Ideal R is an abbreviation for Submodule R R
#check (Ideal R : Type _)

-- An ideal is closed under addition
recall Ideal.add_mem {α : Type*} [Semiring α] (I : Ideal α)
    {a b : α} : a ∈ I → b ∈ I → a + b ∈ I

-- The ideal generated by a set (Napkin Definition 4.7.1)
#check @Ideal.span R

-- Principal ideals: (a) = {r * a | r ∈ R} (Napkin Definition 4.7.3)
example (a : R) : Ideal R := Ideal.span {a}

end Ideals

/-! ## Section 4.7: Quotient rings

Napkin Definition 4.7.6: If I is an ideal of R, the **quotient ring**
R ⧸ I is the ring of cosets of I in R.
-/
section QuotientRings

variable {R : Type*} [CommRing R] (I : Ideal R)

-- The quotient ring R ⧸ I
#check (R ⧸ I : Type _)

-- The quotient is a ring
example : CommRing (R ⧸ I) := inferInstance

-- The canonical surjection R → R ⧸ I
#check @Ideal.Quotient.mk R _ I

end QuotientRings

/-! ## Section 4.8: Principal ideal domains

Napkin Definition 4.8.1: A ring R is a **principal ideal domain** (PID)
if R is an integral domain and every ideal of R is principal.
-/
section PIDs

#check (IsPrincipalIdealRing : ∀ (R : Type*) [inst : Semiring R], Prop)

-- ℤ is a PID
example : IsPrincipalIdealRing ℤ := inferInstance

end PIDs

/-! ## Section 4.9: Noetherian rings

Napkin Definition 4.9.1: A ring R is **Noetherian** if every ideal
of R is finitely generated (equivalently, the ascending chain condition holds).
-/
section Noetherian

#check (IsNoetherianRing : ∀ (R : Type*) [inst : Semiring R], Prop)

-- Every PID is Noetherian
example : IsNoetherianRing ℤ := inferInstance

end Noetherian

/-! ## Exercises -/
section Exercises

variable {R : Type*} [CommRing R]

-- Note: these are all in Mathlib, so `exact?` will find them trivially.
-- The point is to prove them from the ring axioms directly.

/-- Exercise 4A: Show that in any ring, 0 * a = 0. -/
theorem exercise_4A (a : R) : 0 * a = 0 := by
  sorry

/-- Exercise 4B: Show that (-1) * a = -a. -/
theorem exercise_4B (a : R) : -1 * a = -a := by
  sorry

/-- Exercise 4C: Show that the kernel of a ring homomorphism is closed under
addition. -/
theorem exercise_4C {S : Type*} [CommRing S] (f : R →+* S)
    {a b : R} (ha : f a = 0) (hb : f b = 0) : f (a + b) = 0 := by
  sorry

/-- Exercise 4D: Show that if I is a maximal ideal of R, then every nonzero
element of R ⧸ I has a multiplicative inverse. -/
theorem exercise_4D (I : Ideal R) [I.IsMaximal]
    (x : R ⧸ I) (hx : x ≠ 0) : ∃ y : R ⧸ I, x * y = 1 := by
  sorry

end Exercises
