import Mathlib.RingTheory.Ideal.Quotient.Basic
import Mathlib.RingTheory.Ideal.Span
import Mathlib.RingTheory.PrincipalIdealDomain
import Mathlib.Tactic

/-! # Chapter 4: Rings and ideals

This file formalizes Chapter 4 of Evan Chen's
*An Infinitely Large Napkin*, covering rings, fields,
ring homomorphisms, ideals, and quotient rings.

## References
* [Evan Chen, *An Infinitely Large Napkin*](https://venhance.github.io/napkin/Napkin.pdf), Chapter 4
-/

/-! ## Section 4.3: Definition and examples of rings

Napkin Definition 4.3.1: A **ring** $(R, +, \times)$ is a set $R$ equipped
with addition (forming an abelian group) and multiplication (associative with
identity), satisfying the distributive laws.

In Mathlib, `Ring R` extends `Semiring R` and `AddCommGroup R`.
-/
section RingDefinition

#check (Ring : Type _ → Type _)
#check (CommRing : Type _ → Type _)

end RingDefinition

/-! ### Examples of rings (Napkin Example 4.3.2) -/
section RingExamples

-- The integers
example : CommRing ℤ := inferInstance

-- ℤ/nℤ
example (n : ℕ) : CommRing (ZMod n) := inferInstance

-- Polynomials over a ring
noncomputable example (R : Type*) [CommRing R] : CommRing (Polynomial R) := inferInstance

-- Matrices
example (n : ℕ) (R : Type*) [CommRing R] [DecidableEq (Fin n)] :
    Ring (Matrix (Fin n) (Fin n) R) := inferInstance

end RingExamples

/-! ## Section 4.4: Fields

Napkin Definition 4.4.1: A **field** is a commutative ring in which
every nonzero element has a multiplicative inverse.

In Mathlib, `Field K` extends `CommRing K` and `DivisionRing K`.
-/
section Fields

#check (Field : Type _ → Type _)

-- Examples
example : Field ℚ := inferInstance
noncomputable example : Field ℝ := inferInstance
noncomputable example : Field ℂ := inferInstance
example (p : ℕ) [Fact (Nat.Prime p)] : Field (ZMod p) := inferInstance

end Fields

/-! ## Section 4.5: Ring homomorphisms

Napkin Definition 4.5.1: A **ring homomorphism** $\phi : R \to S$ is a
map satisfying $\phi(a + b) = \phi(a) + \phi(b)$,
$\phi(ab) = \phi(a)\phi(b)$, and $\phi(1_R) = 1_S$.

In Mathlib, this is `RingHom` (notation: `R →+* S`).
-/
section RingHomomorphisms

variable {R S : Type*} [Ring R] [Ring S]

#check @RingHom

-- A ring homomorphism preserves the key operations
#check @RingHom.map_add
#check @RingHom.map_mul
#check @RingHom.map_one
#check @RingHom.map_zero

end RingHomomorphisms

/-! ## Section 4.6: Ideals

Napkin Definition 4.6.1: An **ideal** $I$ of a ring $R$ is a nonempty
subset closed under addition and closed under multiplication by any
element of $R$ (i.e. $I$ is a submodule of $R$ over itself).

In Mathlib, `Ideal R` is defined as `Submodule R R`.
-/
section Ideals

variable {R : Type*} [CommRing R]

-- Ideal R is an abbreviation for Submodule R R
#check (Ideal R : Type _)

-- An ideal is closed under addition and scalar multiplication
#check @Ideal.add_mem R
#check @Submodule.smul_mem R R

-- The ideal generated by a set (Napkin Definition 4.7.1)
#check @Ideal.span R

-- Principal ideals: ⟨a⟩ = {ra | r ∈ R} (Napkin Definition 4.7.3)
example (a : R) : Ideal R := Ideal.span {a}

end Ideals

/-! ## Section 4.7: Quotient rings

Napkin Definition 4.7.6: If $I$ is an ideal of $R$, the **quotient ring**
$R/I$ is the ring of cosets of $I$ in $R$.
-/
section QuotientRings

variable {R : Type*} [CommRing R] (I : Ideal R)

-- The quotient ring R / I
#check (R ⧸ I : Type _)

-- The quotient is a ring
example : CommRing (R ⧸ I) := inferInstance

-- The canonical surjection R → R/I
#check @Ideal.Quotient.mk R _ I

end QuotientRings

/-! ## Section 4.8: Principal ideal domains

Napkin Definition 4.8.1: A ring $R$ is a **principal ideal domain** (PID)
if $R$ is an integral domain and every ideal of $R$ is principal.
-/
section PIDs

#check (IsPrincipalIdealRing : ∀ (R : Type*) [inst : Semiring R], Prop)

-- ℤ is a PID
example : IsPrincipalIdealRing ℤ := inferInstance

end PIDs

/-! ## Section 4.9: Noetherian rings

Napkin Definition 4.9.1: A ring $R$ is **Noetherian** if every ideal
of $R$ is finitely generated (equivalently, the ascending chain condition holds).
-/
section Noetherian

#check (IsNoetherianRing : ∀ (R : Type*) [inst : Semiring R], Prop)

-- Every PID is Noetherian
example : IsNoetherianRing ℤ := inferInstance

end Noetherian

/-! ## Exercises -/
section Exercises

variable {R : Type*} [CommRing R]

/-- Exercise 4A: Show that in any ring, $0 \cdot a = 0$. -/
recall zero_mul {R : Type*} [MulZeroClass R] (a : R) : 0 * a = 0

/-- Exercise 4B: Show that $(-1) \cdot a = -a$. -/
recall neg_one_mul {α : Type*} [MulOneClass α] [HasDistribNeg α] (a : α) :
    -1 * a = -a

/-- Exercise 4C: Show that the kernel of a ring homomorphism is an ideal. -/
-- This is `RingHom.ker` in Mathlib
example {S : Type*} [CommRing S] (f : R →+* S) : Ideal R := RingHom.ker f

/-- Exercise 4D: Show that the quotient of a commutative ring by a maximal
ideal is a field. -/
-- This is `Ideal.Quotient.field` in Mathlib
noncomputable example (I : Ideal R) [I.IsMaximal] : Field (R ⧸ I) :=
  Ideal.Quotient.field I

end Exercises
