import Mathlib.LinearAlgebra.Determinant
import Mathlib.LinearAlgebra.Matrix.Charpoly.Basic
import Mathlib.LinearAlgebra.ExteriorAlgebra.Basic
import Mathlib.Tactic

/-! # Chapter 14: Determinant

This file formalizes the determinant chapter of Evan Chen's
*An Infinitely Large Napkin*, covering the wedge product,
determinant, characteristic polynomial, and Cayley-Hamilton.

## References
* [Evan Chen, *An Infinitely Large Napkin*](https://venhance.github.io/napkin/Napkin.pdf), Chapter 14
-/

/-! ## Section 14.1: Wedge product

Napkin Definition 14.1.1: The **wedge product** (or exterior product)
∧ᵐ(V) is generated by v₁ ∧ ··· ∧ vₘ subject to multilinearity
and the alternating property (v ∧ v = 0).
-/
section WedgeProduct

#check @ExteriorAlgebra
#check @AlternatingMap

end WedgeProduct

/-! ## Section 14.2: The determinant

Napkin Definition 14.2.3: The **determinant** of T : V → V is the
scalar c such that ∧ⁿ(T) acts as multiplication by c on the
one-dimensional space ∧ⁿ(V).
-/
section Determinant

variable {R : Type*} [CommRing R]

-- Determinant of a linear map
#check @LinearMap.det R

-- Determinant of a matrix
#check @Matrix.det

-- det(A * B) = det(A) * det(B)
recall Matrix.det_mul {n : Type*} [DecidableEq n] [Fintype n]
    {R : Type*} [CommRing R]
    (M N : Matrix n n R) : (M * N).det = M.det * N.det

end Determinant

/-! ## Section 14.3: Characteristic polynomial and Cayley-Hamilton

Napkin Theorem 14.3.3 (Cayley-Hamilton): If p(x) is the characteristic
polynomial of T, then p(T) = 0.
-/
section CayleyHamilton

variable {R : Type*} [CommRing R] {n : Type*} [DecidableEq n] [Fintype n]

-- The characteristic polynomial
#check @Matrix.charpoly

-- Cayley-Hamilton theorem
recall Matrix.aeval_self_charpoly {R : Type*} [CommRing R]
    {n : Type*} [DecidableEq n] [Fintype n]
    (M : Matrix n n R) : (Polynomial.aeval M) M.charpoly = 0

end CayleyHamilton

/-! ## Exercises -/
section Exercises

-- Note: these are all in Mathlib, so exact? will find them trivially.
-- The point is to prove them from first principles.

variable {R : Type*} [CommRing R] {n : Type*} [DecidableEq n] [Fintype n]

/-- Exercise 14A: det(A * B) = det(A) * det(B). -/
theorem exercise_14A (A B : Matrix n n R) :
    (A * B).det = A.det * B.det := by
  sorry

end Exercises
